export const LOAD_BLOG_SUCCESS = "LOAD_BLOG_SUCCESS";
export const CREATE_BLOG_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const DELETE_BLOG_OPTIMISTIC = "DELETE_BLOG_OPTIMISTIC";